"""
The 10-Q reports nearly every financial metric across FOUR overlapping
time windows on the same page:
    - Three Months Ended June 25, 2022   (Q3 2022)
    - Three Months Ended June 26, 2021   (Q3 2021)
    - Nine Months Ended June 25, 2022    (9mo 2022)
    - Nine Months Ended June 26, 2021    (9mo 2021)

"Net sales" alone appears as $82,959M / $81,434M / $304,182M / $282,457M
within a few inches of each other. Semantic similarity CANNOT tell these
apart, all four chunks are about "net sales" and will score similarly
against the query "what were Apple's net sales?".

The fix I used is metadata
filtering : tag every chunk with which fiscal
period(s) it covers, then let retrieval filter/boost on that tag before
(or in addition to) semantic similarity, and force the generation prompt
to ask for disambiguation when a query doesn't specify a period.

This module adds, to every chunk-sized unit of content:
  - fiscal_periods: list of period tags detected in that unit
  - section: nearest preceding heading (e.g. "Note 3 - Financial
    Instruments", "Item 2. Management's Discussion and Analysis")
  - statement_type: coarse classification (income_statement, balance_sheet,
    cash_flow, equity, segment, notes, mdna, legal, other) via keyword match
  - filing_page_label: the human-readable page footer, for citation
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


# Period detection
PERIOD_PATTERNS = {
    "Q3_2022": re.compile(r"three\s+months\s+ended\s*june\s*25,?\s*2022|june\s*25,?\s*2022", re.I),
    "Q3_2021": re.compile(r"three\s+months\s+ended\s*june\s*26,?\s*2021|june\s*26,?\s*2021", re.I),
    "NINE_MO_2022": re.compile(r"nine\s+months\s+ended\s*june\s*25,?\s*2022", re.I),
    "NINE_MO_2021": re.compile(r"nine\s+months\s+ended\s*june\s*26,?\s*2021", re.I),
    "FY2021_SEPT": re.compile(r"september\s*25,?\s*2021", re.I),
}

# A table showing BOTH "Three Months Ended" and "Nine Months Ended" headers(ambiguity case)
# tag it as multi-period explicitly so the
# retrieval/prompt layer knows to disambiguate rather than picking one.


STRUCTURAL_3MO = re.compile(r"three\s+months\s+ended", re.I)
STRUCTURAL_9MO = re.compile(r"nine\s+months\s+ended", re.I)


def detect_periods(text: str) -> list[str]:
    hits = []
    for tag, pattern in PERIOD_PATTERNS.items():
        if pattern.search(text):
            hits.append(tag)

    # Fallback: this filing wraps its period header across multiple physical lines ("Three Months Ended / Nine Months Ended" on one line
    # "June 25, June 26, ..." on the next, "2022 2021 ..." on a
    # third), so the exact-phrase date patterns above can miss it even
    # though the table unambiguously spans both windows. Rather than
    # silently under-tagging fall back to structural markers: if both
    # "Three Months Ended" and "Nine Months Ended" appear, tag it as
    # spanning both granularities even without a precisely matched date.
    if not hits and STRUCTURAL_3MO.search(text) and STRUCTURAL_9MO.search(text):
        hits.extend(["QUARTERLY_GENERIC", "NINE_MONTH_GENERIC"])

    return hits



# Section / heading detection

SECTION_HEADING_PATTERNS = [
    re.compile(r"^Item\s+\d+[A-Z]?\.\s+.+", re.I),
    re.compile(r"^Note\s+\d+\s*[–-]\s*.+", re.I),
    re.compile(r"^PART\s+[IVX]+", re.I),
    re.compile(
        r"^(CONDENSED CONSOLIDATED (STATEMENTS?|BALANCE SHEETS?) OF .+)$", re.I
    ),
]


def find_section_heading(lines: list[str]) -> str | None:
    for line in lines:
        for pat in SECTION_HEADING_PATTERNS:
            if pat.match(line.strip()):
                return line.strip()
    return None



# Coarse statement-type classification (keyword based)
STATEMENT_TYPE_KEYWORDS = {
    "income_statement": ["net sales", "cost of sales", "gross margin", "operating income", "earnings per share"],
    "balance_sheet": ["total assets", "total liabilities", "shareholders’ equity", "shareholders' equity"],
    "cash_flow": ["cash generated by operating", "investing activities", "financing activities"],
    "equity": ["retained earnings", "common stock and additional paid-in capital"],
    "segment": ["reportable segment", "americas", "greater china", "segment operating income"],
    "financial_instruments": ["marketable securities", "derivative instruments", "fair value"],
    "legal": ["legal proceedings", "litigation", "lawsuit"],
    "mdna": ["management’s discussion", "management's discussion", "forward-looking statements"],
}


def classify_statement_type(text: str) -> str:
    lowered = text.lower()
    best_type, best_score = "other", 0
    for stype, keywords in STATEMENT_TYPE_KEYWORDS.items():
        score = sum(1 for kw in keywords if kw in lowered)
        if score > best_score:
            best_type, best_score = stype, score
    return best_type


# Enrichment entry point, operates on the parsed_document.json from parse_pdf.py and annotates in place before chunking.
def enrich_document(parsed_doc: dict) -> dict:
    current_section = None

    for page in parsed_doc["pages"]:
        lines = page["narrative_text"].splitlines()
        heading = find_section_heading(lines)
        if heading:
            current_section = heading

        page["section"] = current_section
        page["fiscal_periods_detected"] = detect_periods(page["narrative_text"])
        page["statement_type"] = classify_statement_type(page["narrative_text"])

        for table in page["tables"]:
            # header_context is the text zone directly above the table (from parse_pdf.py) for tables like the income statement,
            period_source = (
                table.get("header_context", "")
                + " " + table["caption"]
                + " " + " ".join(" ".join(r) for r in table["rows"][:4])
            )
            table_text_blob = table["caption"] + " " + " ".join(
                " ".join(row) for row in table["rows"][:3]  # header rows are enough
            )
            table["section"] = current_section
            table["fiscal_periods_detected"] = detect_periods(period_source)
            table["statement_type"] = classify_statement_type(table_text_blob)
            table["is_multi_period"] = len(table["fiscal_periods_detected"]) > 1

    return parsed_doc


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "data/parsed_document.json"
    out = sys.argv[2] if len(sys.argv) > 2 else "data/parsed_document.enriched.json"

    with open(src, "r", encoding="utf-8") as f:
        parsed = json.load(f)

    enriched = enrich_document(parsed)

    Path(out).parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(enriched, f, indent=2)

    multi_period_tables = sum(
        1 for p in enriched["pages"] for t in p["tables"] if t.get("is_multi_period")
    )
    print(f"Enriched {len(enriched['pages'])} pages. "
          f"{multi_period_tables} tables flagged multi-period (ambiguity risk).")